# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16afaebb630804ef01b00dfa16f75bd207a22712be258842280472c8e59119db0d1ecdffffd542a036c9ebbc5c9384b376367da7d65147dce1a6f7185bda73a9

test:
  secret_key_base: 788e7bd5657029a580bc28bd1adccb8a888b849ecaf396672fbc49f7228f09cae960c4777e3e312beb4a63390dec10207b1c8703eea34f123f178cdd6b010019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
